export const fakeData: any = [
    {
      date: "02/27/2023",
      task_num: 1001,
      task_details: "פירוט משימה לדגומא",
      name_space: "ACC",
      signature: "Itay Eylath",
      class: "class",
      program_name: "WBLR",
      label: "label",
      related_programs: "WBLR",
      dev_server: "example cache test (111.222.333.44)",
      update_dev_server: "02/27/2023",
      update_4_server: "02/27/2023",
      update_prod_server: "update_prod_server",
      project_manager: "יוני חנוני",
      client: "גשר גולן",
      status: "בוצע",
      comments: "הערה לדוגמא",
    },
    {
      date: "02/27/2023",
      task_num: 1001,
      task_details: "פירוט משימה לדגומא",
      name_space: "ACC",
      signature: "Itay Eylath",
      class: "class",
      program_name: "WBLR",
      label: "label",
      related_programs: "WBLR",
      dev_server: "example cache test (111.222.333.44)",
      update_dev_server: "02/27/2023",
      update_4_server: "02/27/2023",
      update_prod_server: "update_prod_server",
      project_manager: "יוני חנוני",
      client: "גשר גולן",
      status: "בוצע",
      comments: "הערה לדוגמא",
    },
    {
      date: "02/27/2023",
      task_num: 1002,
      task_details: "פירוט משימה לדגומא",
      name_space: "ACC",
      signature: "Itay Eylath",
      class: "class",
      program_name: "WBLR",
      label: "label",
      related_programs: "WBLR",
      dev_server: "example cache test (111.222.333.44)",
      update_dev_server: "02/27/2023",
      update_4_server: "02/27/2023",
      update_prod_server: "update_prod_server",
      project_manager: "יוני חנוני",
      client: "גשר גולן",
      status: "בוצע",
      comments: "הערה לדוגמא",
    },
    {
      date: "02/27/2023",
      task_num: 1003,
      task_details: "פירוט משימה לדגומא",
      name_space: "ACC",
      signature: "Itay Eylath",
      class: "class",
      program_name: "WBLR",
      label: "label",
      related_programs: "WBLR",
      dev_server: "example cache test (111.222.333.44)",
      update_dev_server: "02/27/2023",
      update_4_server: "02/27/2023",
      update_prod_server: "update_prod_server",
      project_manager: "יוני חנוני",
      client: "גשר גולן",
      status: "בוצע",
      comments: "הערה לדוגמא",
    },
    {
      date: "02/27/2023",
      task_num: 1004,
      task_details: "פירוט משימה לדגומא",
      name_space: "ACC",
      signature: "Itay Eylath",
      class: "class",
      program_name: "WBLR",
      label: "label",
      related_programs: "WBLR",
      dev_server: "example cache test (111.222.333.44)",
      update_dev_server: "02/27/2023",
      update_4_server: "02/27/2023",
      update_prod_server: "update_prod_server",
      project_manager: "יוני חנוני",
      client: "גשר גולן",
      status: "בוצע",
      comments: "הערה לדוגמא",
    },
  ];